Health/BMI Tracker
mrco245/SWENG861-Group3 pull request #5
Opened 2024-10-03 01:37 UTC by stm5645

- Created Health Homepage
- Two Buttons for BMI entry and history
- Frontend and Backend should be good to go, but would like to make more changes especially if needed.
- One final thing I need to do is unit testing for this feature.

<img width="1569" alt="Screen Shot 2024-10-02 at 9 27 34 PM" src="https://github.com/user-attachments/assets/a111084a-f9e1-462a-8c2c-2580c3672ecf">

<img width="1474" alt="Screen Shot 2024-10-02 at 9 27 45 PM" src="https://github.com/user-attachments/assets/cb4e448a-5129-40d9-afec-3e88db4046c4">

<img width="1292" alt="Screen Shot 2024-10-02 at 9 27 57 PM" src="https://github.com/user-attachments/assets/9c3932d5-d806-442b-9c28-8ef17c0bf2ed">

<img width="1445" alt="Screen Shot 2024-10-02 at 9 37 11 PM" src="https://github.com/user-attachments/assets/834ffce9-0045-4118-baf3-603bc00bb9b1">

2024-10-03 02:02 UTC, mrco245 commented
So when I tried to run this: 
![image](https://github.com/user-attachments/assets/2a25a6f4-6311-42d8-8968-66f06aa2a155)
 
 I did do a npm install to just make sure it wasn't me. So make sure to add any npm packages to the package.json file that you included.

2024-10-03 02:03 UTC, mrco245 commented on client/src/pages/Friends.jsx
If this is part of your changes, its fine to leave it - but I would probably remove since this will be in brandon's work. 
Unless your health relies on it.

2024-10-03 02:07 UTC, mrco245 requested changes
I would probably remove any of the "friends" functionality - unless you need it for your items to work. 

Make sure to update the package.json files with any libraries you added.

2024-10-03 23:15 UTC, stm5645 commented on client/src/pages/Friends.jsx
Nope, I can remove it! I think I had it originally because I pulled from that branch by mistake.

2024-10-03 23:29 UTC, stm5645 commented
Just made the changes. Now just need to do unit testing

2024-10-04 01:07 UTC, mrco245 commented on client/src/App.jsx
> +        <Route path='/friends' element={<Friends />} />
make sure to remove here too.

2024-10-04 01:18 UTC, mrco245 commented
Also not sure, but when i logged into my account - i already had bmi history? that doesnt seem right...

2024-10-04 01:21 UTC, mrco245 commented on client/src/pages/Health.jsx
> +          placeholder="Enter your weight (kg)"
is this expecting the value has to be in kg? or what if im american and only know lbs?

2024-10-04 01:21 UTC, mrco245 commented on client/src/pages/Health.jsx
> +          placeholder="Enter your height (m)"
does this only accept meters or what if i enter it in feet and inches?

2024-10-04 01:21 UTC, mrco245 commented on client/src/pages/Health.jsx
> +          <button className="submit-btn" onClick={calculateBmi} disabled={isLoading}>
you could also disable if the form is not valid.

2024-10-04 03:33 UTC, stm5645 commented
Unit testing is done and did some bug fixes (both frontend and backend) too.

2024-10-04 13:11 UTC, stm5645 commented
there's also a delete option in BMI history for users to delete certain past BMI entries

2024-10-04 15:15 UTC, mrco245 commented
Make sure to pull develop into your branch

2024-10-04 15:20 UTC, mrco245 commented
Also I didn't see any unit tests for the client code, are you still working on those?

2024-10-04 16:09 UTC, stm5645 commented
Just need to include the unit testing for client

2024-10-04 18:22 UTC, mrco245 approved these changes

2024-10-04 21:40 UTC, merged